.TH NASH 8 "Sat Mar 27 1999"
.UC 4
.SH NAME
nash \- script interpretor to interpret linuxrc images
.SH SYNOPSIS
\fBnash\fR [--force] \fIscript\fR

.SH DESCRIPTION
\fBnash\fR is a very simple script interpretor designed to be as small as
possible. It is primarily designed to run simple linuxrc scripts on an initrd
image. Arguments to commands may be enclosed in either single or double
quotes to allow spaces to be included in the arguments. Spaces outside of
quotations always delineate arguments, and so backslash escaping is supported.

Additionally, if nash is invoked as \fBmodprobe\fR, it will immediately
exit with a return code of zero. This is to allow initrd's to prevent some
extraneous kernel error messages during startup.

There are two types of commands, built in and external. External commands
are run from the filesystem via execve(). If commands names are given without
a path, nash will search it's builtin PATH, which is /usr/bin, /bin,
/sbin, /usr/sbin.

Currently, \fBnash\fR supports the following built in commands.

.TP
\fBecho [item]* [> \fIfilename\fR]\fR
Echos the text strings given to a file, with a space in between each
item. The output may be optionally redirected to a file.

\fBexec\fR \fI<command>\fR
The command given is execed, overlaying the nash process.

.TP
\fBlosetup \fI/dev/loopdev\fR \fIfile\fR
Binds \fIfile\fR to the loopback device \fI/dev/loopdev\fR. See
\fBlosetup(8)\fR for information on loopback devices.

\fBmkdir\fR \fI[-p]\fR \fIpath\fR
Creates the directory \fIpath\fR. If \fI-p\fR is specified, this command
will not complain if the directory exists. Note this is a subset of the
standard \fBmkdir\fR \fI-p\fR behavior.

.TP
\fBmkrootdev \fIpath\fR
Makes \fIpath\fR a block inode for the device whose device number is
/proc/sys/kernel/real-root-dev.

.TP
\fBmount \fI[--ro] -t \fItype\fR \fIdevice\fR \fImntpoint\fR
Mounts a filesystem. It does not support NFS, and it must be used in
\fBexactly\fR the form given above. If \fI--ro\fR is given, the filesystem
is mounted read only.

.TP
\fBpivot_root \fInewrootpath\fR \fIoldrootpath\fR
Makes the filesystem mounted at \fInewrootpath\fR the new root filesystem,
and mounts the current root filesystem as \fIoldrootpath\fR.

.TP
\fBraidautorun \fImddevice\fR
Runs raid autodetection on all raid-typed partitions. \fImddevice\fR must
be a raid device (any will do).

.TP
\fBumount \fIpath\fR
Unmounts the filesystem mounted at \fIpath\fR.

.SH OPTIONS
.TP
\fB-\-force\fR
Allows \fBforce\fR really execute the script, even though \fBnash\fR doesn't 
appear to be running from an initrd image.

.SH BUGS
Probably many. \fBnash\fR is \fbnot a shell\fR, and it shouldn't be though of
as one. It isn't entirely different from a shell, but that's mostly by
accident.

.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
