.TH GRUBBY 8 "Thu Jun 21 2002"
.UC 4
.SH NAME
grubby \- command line tool for configuring grub, lilo, and elilo

.SH SYNOPSIS
\fBgrubby\fR [--add-kernel=\fIkernel-path\fR] [--args=\fIargs\fR] 
       [--bad-image-okay] [--boot-filesystem=\fIbootfs\fR] 
       [--bootloader-probe] [--config-file \fIpath\fR] 
       [--copy-default] [--default-kernel] [--grub] 
       [--info=\fIkernel-path\fR] [--initrd=\fIinitrd-path\fR] 
       [--lilo] [--make-default] [-o path] 
       [--remove-kernel=\fIkernel-path\fR] 
       [--set-default=\fIkernel-path\fR] [--title=entry-title] 

.SH DESCRIPTION
\fBgrubby\fR is a command line tool for updating and displaying information
about the configuration files for the \fBgrub\fR, \fBlilo\fR, and \fBelilo\fR 
(ia64) boot loaders. It is primarily designed to be used from scripts
which install new kernels and need to find information about the current
boot environment.

On Intel x86 platforms, \fBgrub\fR is the default bootloader and the
configuration file is in \fB/boot/grub/grub.conf\fR. On
Intel ia64 platforms, \fBlilo\fR mode is used (elilo is almost entirely
configuration compatible with lilo) and the default location for the
configuration file is \fB/boot/grub/grub.conf\fR.

When a kernel path is specified for the \fB-\-info\fR, 
\fB-\-remove-kernel\fR, or \fB-\-update-kernel\fR,
\fBDEFAULT\fR selects the default kernel entry and
\fBALL\fR selects all of the kernel entries. If a number is used for
the kernel path the entry specified by the number is selected. All of the
valid indexes are display when \fB-\-info=ALL\fR is used.

.SH OPTIONS
.TP
\fB-\-add-kernel\fR=\fIkernel-path\fR
Add a new boot entry for the kernel located at \fIkernel-path\fR.

.TP
\fB-\-args\fR=\fIkernel-args\fR
When a new kernel is added, this specifies the command line arguments
which should be passed to the kernel by default. When \fB-\-update-kernel\fR
is used, this specifies new arguments to add to the argument list. Multiple,
space separated arguments may be used. If an argument already exists the
new value replaces the old values. The \fBroot=\fR kernel argument gets
special handling if the configuration file has special handling for specifying
the root filesystem (like lilo.conf does).

.TP
\fB-\-bad-image-okay\fR
When \fBgrubby\fR is looking for a entry to use for something (such
as a template or a default boot entry) it uses sanity checks, such as
ensuring that the kernel exists in the filesystem, to make sure
entries that obviously won't work aren't selected. This option overrides
that behavior, and is designed primarily for testing.

.TP
\fB-\-boot-filesystem\fR=\fIbootfs\fR
The \fBgrub\fR boot loader expects file paths listed in it's configuration
path to be relative to the top of the filesystem they are on, rather then
relative to the current root filesystem. By default \fBgrubby\fR searches
the list of currently mounted filesystems to determine this. If this option
is given \fBgrubby\fR acts as if the specified filesystem was the filesystem
containing the kernel (this option is designed primarily for testing).

.TP
\fB-\-bootloader-probe\fR
\fBgrubby\fR tries to determine if \fBgrub\fR or \fBlilo\fR is currently 
installed. When one of those bootloaders is found the name of that bootloader
is displayed on stdout.  Both could be installed (on different devices), and
grubby will print out the names of both bootloaders, one per line. The probe
for \fBgrub\fR requires a commented out boot directive \fBgrub.conf\fR
identical to the standard directive in the lilo configuration file. If this
is not present \fBgrubby\fR will assume grub is not installed (note 
that \fBanaconda\fR places this directive in \fBgrub.conf\fR files it creates).
This option is only available on ia32 platforms. 


.TP
\fB-\-config-file\fR=\fIpath\fR
Use \fIpath\fR as the configuration file rather then the default.

.TP
\fB-\-copy-default\fR
\fBgrubby\fR will copy as much information (such as kernel arguments and
root device) as possible from the current default kernel. The kernel path
and initrd path will never be copied.

.TP
\fB-\-default-kernel\fR
Display the full path to the current default kernel and exit.

.TP
\fB-\-grub\fR
Use a \fBgrub\fR style configuration file instead of \fBlilo\fR style. This
is the default on ia32 platforms.

.TP
\fB-\-info\fR=\fIkernel-path\fR
Display information on all boot entries which match \fIkernel-path\fR. I

.TP
\fB-\-initrd\fR=\fIinitrd-path\fR
Use \fIinitrd-path\fR as the path to an initial ram disk for a new kernel
being added.

.TP
\fB-\-lilo\fR
Use a \fBlilo\fR style configuration file instead of \fBgrub\fR style. This
is the default on ia64 platforms. On ia32 platforms this option changes the
default configuration file path to \fB/etc/lilo.conf\fR.

.TP
\fB-\-make-default\fR
Make the new kernel entry being added the default entry.

.TP
\fB-\-remove-args\fR=\fIkernel-args\fR
The arguments specified by \fIkernel-args\fR are removed from the 
kernels specified by \fB-\-update-kernel\fR. The \fBroot\fR argument
gets special handling for configuration files that support separate root
filesystem configuration.

.TP
\fB-\-remove-kernel\fR=\fIkernel-path\fR
Removes all boot entries which match \fIkernel-path\fR.

.TP
\fB-\-set-default\fR=\fIkernel-path\fR
The first entry which boots the specified kernel is made the default
boot entry.

.TP
\fB-\-title\fR=\fIentry-path\fR
When a new kernel entry is added \fIentry-path\fR is used as the title
(\fBlilo\fR label) for the entry.

.TP
\fB-\-update-kernel\fR=\fIkernel-path\fR
The entries for kernels matching \fRkernel-path\fR are updated. Currently
the only items that can be updated is the kernel argument list, which is
modified via the \fB-\-args\fR and \fB-\-remove-args\fR options.

.SH "BUGS"
The command line syntax is more then a little baroque. This probably
won't be fixed as \fBgrubby\fR is only intended to be called from shell
scripts which can get it right.

.SH "SEE ALSO"
.BR grub (8),
.BR lilo (8),
.BR mkinitrd (8)

.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
