.TH INSTALLKERNEL 8 "Sun Oct 14 2018"
.SH NAME
installkernel \- tool to script kernel installation

.SH SYNOPSIS
\fBinstallkernel\fR \fI<kernel-version> <bootimage> <mapfile>\fR

.SH DESCRIPTION
\fBinstallkernel\fR installs a new kernel image onto the system from
the Linux source tree. It is called by the Linux kernel makefiles when
\fBmake install\fR is invoked there.

The new kernel is installed into {directory}/vmlinuz-{version}. If a
symbolic link {directory}/vmlinuz already exists, it is refreshed by
making a link from {directory}/vmlinuz to the new kernel, and the
previously installed kernel is available as {directory}/vmlinuz.old.

.SH "EXIT STATUS"

This script makes use of the kernel-install program. Specifically, if
every executable returns 0 or 77, then 0 is returned.

In the event of an error or failure, then a non-zero code is returned.

.SH "SEE ALSO"
.BR grubby(8)
.BR new-kernel-pkg(8)

.SH AUTHORS
.nf
Erik Troan
Jeremy Katz
Peter Jones
.fi
