.TH MKINITRD 8 "Sat Mar 27 1999"
.UC 4
.SH NAME
mkinitrd \- creates initial ramdisk images for preloading modules
.SH SYNOPSIS
\fBmkinitrd\fR [-fv] [--with=\fImodule\fR] [--preload=\fImodule\fR] 
         [--omit-scsi-modules] [--omit-raid-modules] 
         [--version] [--fstab=\fIfstab\fR] \fIimage\fR 
         \fIkernel-version\fR
.SH DESCRIPTION
\fBmkinitrd\fR creates filesystem images which are suitable for use
as Linux initial ramdisk (initrd) images. Such images are often
used for preloading the block device modules (such as SCSI or RAID)
which are needed to access the root filesystem. \fBmkinitrd\fR
automatically loads all \fIscsi_hostadapter\fR entries in
\fI/etc/modules.conf\fR, which makes it simple to build and use kernels
using moduler SCSI devices.

Any module options specified in \fI/etc/modules.conf\fR are passed
to the modules as they are loaded by the initial ramdisk.

If the root device is on a loop device (such as /dev/loop0), \fBmkinitrd\fR
will attempt to build an initrd which sets up the loopback file properly.
To do this, the fstab must contain a comment of the form:

    # LOOP0: /dev/hda1 vfat /linux/rootfs

LOOP0 must be the name of the loop device which needs to be configured, in
all capital lettes. The parameters after the color are the device which 
contains the filesystem with the loopback image on it, the filesystem which
is on the device, and the full path to the loopback image. If the filesystem
is modular, initrd will automatically add the filesystem's modules to the
initrd image.

.SH OPTIONS
.TP
\fB-f\fR
Allows \fBmkinitrd\fR to overwrite an existing image file.

.TP
\fB-\-fstab=\fR\fIfstab\fR
Use \fIfstab\fR to automatically determine what type of filesystem the
root device is on. Normally, \fB/etc/fstab\fR is used.

.TP
\fB-\-ifneeded
Only builds the image if there are modules that need to be loaded at boot
time.

.TP
\fB-\-omit-scsi-modules 
Do not load any scsi modules, including 'scsi_mod' and 'sd_mod'
modules, even if they are present.

.TP
\fB-\-omit-raid-modules 
Do not load any raid modules, even if /etc/fstab and /etc/raidtab expect them.

.TP
\fB-\-preload=\fR\fImodule\fR
Load the module \fImodule\fR in the initial ramdisk image. The module gets
loaded before any SCSI modules which are specified in \fI/etc/modules.conf\fR.
This option may be used as many times as necessary.

.TP
\fB-v\fR
Prints out verbose information while creating the image (normally
the \fBmkinitrd\fR runs silently). 

.TP
\fB-\-version\fR
Prints the version of \fBmkinitrd\fR that's being used and then exits.

.TP
\fB-\-with=\fR\fImodule\fR
Load the modules \fImodule\fR in the initial ramdisk image. The module
gets loaded after any SCSI modules which are specified in 
\fI/etc/modules.conf\fR. This option may be used as many times as 
necessary.

.SH FILES
.PD 0
.TP 20
\fI/dev/loop*\fR
A block loopback device is used to create the image, which makes this
script useless on systems without block loopback support available.

.TP 20
\fI/etc/modules.conf\fR
Specified SCSI modules to be loaded and module options to be used.
.PD
.SH "SEE ALSO"
.BR fstab (5),
.BR insmod (1),
.BR kerneld (8),
.BR lilo (8)

.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
