.TH MKINITRD 8 "Sat Mar 27 1999"
.UC 4
.SH NAME
mkinitrd \- creates initial ramdisk images for preloading modules
.SH SYNOPSIS
\fBmkinitrd\fR [--version] [-v] [-f] 
         [--preload=\fImodule\fR] [--omit-scsi-modules] 
         [--omit-raid-modules] [--omit-lvm-modules] 
         [--with=\fImodule\fR] [--image-version]
         [--fstab=\fIfstab\fR] [--nocompress]
         [--builtin=\fImodule\fR] [--nopivot]
         \fIimage\fR \fIkernel-version\fR

.SH DESCRIPTION
\fBmkinitrd\fR creates filesystem images which are suitable for use
as Linux initial ramdisk (initrd) images. Such images are often
used for preloading the block device modules (such as IDE, SCSI or RAID)
which are needed to access the root filesystem. \fBmkinitrd\fR
automatically loads filesystem modules (such as ext3 and jbd), IDE modules, all
\fIscsi_hostadapter\fR entries in \fI/etc/modules.conf\fR, and raid
modules if the system's root partition is on raid, which makes it simple
to build and use kernels using modular device drivers.

Any module options specified in \fI/etc/modules.conf\fR are passed
to the modules as they are loaded by the initial ramdisk.

If the root device is on a loop device (such as /dev/loop0), \fBmkinitrd\fR
will build an initrd which sets up the loopback file properly.
To do this, the fstab must contain a comment of the form:

    # LOOP0: /dev/hda1 vfat /linux/rootfs

LOOP0 must be the name of the loop device which needs to be configured, in
all capital lettes. The parameters after the colon are the device which 
contains the filesystem with the loopback image on it, the filesystem which
is on the device, and the full path to the loopback image. If the filesystem
is modular, initrd will automatically add the filesystem's modules to the
initrd image.

The root filesystem used by the kernel is specified in the boot configuration
file, as always. The traditional \fBroot=/dev/hda1\fR style device 
specification is allowed. If a label is used, as in \fBroot=LABEL=rootPart\fR
the initrd will search all available devices for an ext2 or ext3 filesystem
with the appropriate label, and mount that device as the root filesystem.

.SH OPTIONS
.TP
\fB-\-builtin=\fR\fImodule\fR
Act as if \fImodule\fR is built into the kernel being used. \fBmkinitrd\fR
will not look for this module, and will not emit an error if it does not
exist. This option may be used multiple times.

.TP
\fB-f\fR
Allows \fBmkinitrd\fR to overwrite an existing image file.

.TP
\fB-\-fstab=\fR\fIfstab\fR
Use \fIfstab\fR to automatically determine what type of filesystem the
root device is on. Normally, \fB/etc/fstab\fR is used.

.TP
\fB-\-image-version
The kernel version number is appended to the initrd image path before the image
is created.

.TP
\fB-\-nocompress
Normally the created initrd image is compressed with \fBgzip\fR. If this
option is specified, the compression is skipped.

.TP
\fB-\-nopivot
Do not use the \fBpivot_root\fR system call as part of the initrd. This
lets \fBmkinitrd\fR build proper images for Linux 2.2 kernels at the expense
of some features. In particular, some filesystems (such as ext3) will not
work properly and filesystem options will not be used to mount root. This
option is not recommended, and will be removed in future versions.

.TP
\fB-\-omit-lvm-modules 
Do not load any lvm modules, even if /etc/fstab expects them.

.TP
\fB-\-omit-raid-modules 
Do not load any raid modules, even if /etc/fstab and /etc/raidtab expect them.

.TP
\fB-\-omit-scsi-modules 
Do not load any scsi modules, including 'scsi_mod' and 'sd_mod'
modules, even if they are present.

.TP
\fB-\-preload=\fR\fImodule\fR
Load the module \fImodule\fR in the initial ramdisk image. The module gets
loaded before any SCSI modules which are specified in \fI/etc/modules.conf\fR.
This option may be used as many times as necessary.

.TP
\fB-v\fR
Prints out verbose information while creating the image (normally
the \fBmkinitrd\fR runs silently). 

.TP
\fB-\-version\fR
Prints the version of \fBmkinitrd\fR that's being used and then exits.

.TP
\fB-\-with=\fR\fImodule\fR
Load the modules \fImodule\fR in the initial ramdisk image. The module
gets loaded after any SCSI modules which are specified in 
\fI/etc/modules.conf\fR. This option may be used as many times as 
necessary.

.SH FILES
.PD 0
.TP 20
\fI/dev/loop*\fR
A block loopback device is used to create the image, which makes this
script useless on systems without block loopback support available.

.TP 20
\fI/etc/modules.conf\fR
Specified SCSI modules to be loaded and module options to be used.
.PD
.SH "SEE ALSO"
.BR fstab (5),
.BR insmod (1),
.BR kerneld (8),
.BR lilo (8)

.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
